# This is the name of the workflow, which will be displayed on the Actions tab
name: Deploy to Server

# This workflow triggers on a push event to the 'main' branch
on:
  push:
    branches:
      - main # Or 'master', depending on your repository's default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # This step remains the same. It uses your SSH key to log into the server.
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          # The script is updated to use the PAT for the 'git pull' command
          script: |
            # Navigate to the project directory on your server
            cd ${{ secrets.PROJECT_PATH }}

            # Pull the latest changes using the PAT for HTTPS authentication.
            # The 'github.repository' variable automatically provides your 'username/repo-name'.
            echo "Pulling latest code from GitHub..."
            git pull https://x-access-token:${{ secrets.ACTION_PAT }}@github.com/${{ github.repository }}.git main

            # (Optional) Add your build or restart commands here
            # echo "Installing dependencies..."
            # npm install --production
            #
            # echo "Restarting application..."
            # pm2 restart my-app-name

            echo "Deployment complete! 🎉"