name: Deploy to Server

on:
  push:
    branches:
      - main # Or 'master', depending on your repository's default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Updated step to first create the .ssh directory
      - name: Add Server to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      # Your existing deployment step
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            echo "Pulling latest code from GitHub..."
            git pull https://x-access-token:${{ secrets.ACTION_PAT }}@github.com/${{ github.repository }}.git main
            echo "Deployment complete! 🎉"